NowDelivary/Models/MenuCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NowDelivary.Models
{
    public class MenuCategory
    {
        public int ID { get; set; }

        //[Index("IX_UniqueMenuCategory",1,IsUnique =true)]
        public string MenuCategoryType { get; set; }

        [ForeignKey("Place")]
        //[Index("IX_UniqueMenuCategory", 2, IsUnique = true)]
        public int PlaceID { get; set; }
        public Place Place { get; set; }
    }
}

NowDelivary/Controllers/MenuCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NowDelivary.Data;
using NowDelivary.Models;
using NowDelivary.View_Model;
using NowDelivary.ViewModel;

namespace NowDelivary.Controllers
{
    public class MenuCategoryController : Controller
    {

        ApplicationDbContext Context;
        public MenuCategoryController(ApplicationDbContext _context)
        {
            Context = _context;
        }

        public IActionResult GetAll()
        {
            ViewData["area"] = new SelectList(Context.Area, "ID", "AreaName");
            return View();
        }

        public IActionResult GetAllAreaSupermarkets(int areaID)
        {
            PlaceVM vM = new PlaceVM(Context);
            return View(vM.GetAllSupermarket(areaID));
        }

        public IActionResult GetSupermarketSections(int supermarketID)
        {
            PlaceVM vM = new PlaceVM(Context);
            return View(vM.GetSupermarketMenuCategory(supermarketID));
        }

        public IActionResult CreateMenuCategory()
        {
            ViewData["placeID"] = new SelectList(Context.Place, "ID", "PlaceName");

            return View();
        }

        [HttpPost]
        public IActionResult CreateMenuCategory(MenuCategory newmenucategory)
        {
            if (ModelState.IsValid)
            {
                Context.MenuCategorie.Add(newmenucategory);
                Context.SaveChanges();
                return RedirectToAction("GetAll");
            }
            ViewData["placeID"] = new SelectList(Context.Place, "ID", "PlaceName",newmenucategory.PlaceID);
            return View(newmenucategory);
        }
        public async Task<IActionResult> Edite(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("GetAll");
            }
            ViewData["placeID"] = new SelectList(Context.Place, "ID", "PlaceName");

            var getmenuCategorydetails = await Context.MenuCategorie.FindAsync(id);
            return View(getmenuCategorydetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edite(MenuCategory MeCA)
        {
            if (ModelState.IsValid)
            {
                Context.Update(MeCA);
                await Context.SaveChangesAsync();
                return RedirectToAction("GetAll");

            }
            ViewData["placeID"] = new SelectList(Context.Place, "ID", "PlaceName", MeCA.PlaceID);

            return View(MeCA);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("GetAll");
            }
            var getmenuCategorydetails = await Context.MenuCategorie.FindAsync(id);
            return View(getmenuCategorydetails);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {

            var getmenuCategorydetails = await Context.MenuCategorie.FindAsync(id);
            Context.MenuCategorie.Remove(getmenuCategorydetails);
            await Context.SaveChangesAsync();
            return RedirectToAction("GetAll");
        }

    }
}

NowDelivary/Views/MenuCategory/CreateMenuCategory.cshtml
@model MenuCategory
@{
    ViewData["Title"] = "CreateMenuCategory";
}

<h1>CreateMenuCategory</h1>
<Div class="col-md-4">
    <form asp-action="CreateMenuCategory" asp-controller="MenuCategory" method="post">
        <div class="form-group">
            <label asp-for="@Model.MenuCategoryType">Menu Category type</label>
            <input asp-for="@Model.MenuCategoryType" placeholder="Enter Category type" />
        </div>

   
        <div class="form-group">
            <label asp-for="@Model.PlaceID" class="control-label">place</label>
            <select asp-for="@Model.PlaceID" class="form-control" asp-items="ViewBag.placeID"></select>
        </div>

        <button class="btn btn-block btn-success" type="submit">Save</button>
    </form>
</Div>

NowDelivary/Views/MenuCategory/Delete.cshtml
@model MenuCategory
@{
    ViewData["Title"] = "Delete";
}

<Div class="col-md-4">
    <form asp-action="Delete" asp-controller="MenuCategory" method="post">
        <div class="form-group">
            <label asp-for="@Model.MenuCategoryType">Menu item</label>
            <input asp-for="@Model.MenuCategoryType" placeholder="Enter Menu item" />
        </div>
        <div class="form-group">
            <label asp-for="@Model.PlaceID">item Price</label>
            <input asp-for="@Model.PlaceID" placeholder="Enter item Price" />
        </div>
       

        <button class="btn btn-block btn-success" type="submit">Save</button>
    </form>
</Div>

NowDelivary/Views/MenuCategory/Edite.cshtml
@model MenuCategory
@{
    ViewData["Title"] = "Edite";
}

<h1>Edite for menue category</h1>
<Div class="col-md-4">
    <form asp-action="Edite" asp-controller="MenuCategory" method="post">
        <div class="form-group">
            <label asp-for="@Model.MenuCategoryType">Menu item</label>
            <input asp-for="@Model.MenuCategoryType" placeholder="Enter Menu item" />
        </div>
        <div class="form-group">
            <label asp-for="@Model.PlaceID" class="control-label">place</label>
            <select asp-for="@Model.PlaceID" class="form-control" asp-items="ViewBag.placeID"></select>
        </div>
       

        <button class="btn btn-block btn-success" type="submit">Save</button>
    </form>
</Div>

NowDelivary/Views/MenuCategory/GetAll.cshtml
@{
    ViewData["Title"] = "GetAll";
}

    <div class="container">

        @using (Html.BeginForm("GetAllAreaSupermarkets", "MenuCategory",FormMethod.Get))
        {
        <div class="form-group">
            <label for="area">Choose Area</label>
            @Html.DropDownList("areaID", ViewData["area"] as IEnumerable<SelectListItem>, new { id = "area", @class = "browser-default custom-select" })
        </div>
            <div class="form-group">
                <input type="submit" value="Get All supermarkets" class="btn btn-block btn-warning" />
            </div>
        }
    </div>

NowDelivary/Views/MenuCategory/GetAllAreaSupermarkets.cshtml
@model IEnumerable<Place>
@{
    ViewData["Title"] = "GetAllAreaSupermarkets";
}

<table class="table table-hover">
        <thead class="thead-dark">
            <tr style="background-color:black; color:white">
                <th>Supermarket Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var supermarket in Model)
                {
                    <tr>
                        <td>@supermarket.PlaceName</td>
                        <td>
                            <a class="btn btn-block btn-dark" asp-action="GetSupermarketSections" asp-controller="MenuCategory" asp-route-supermarketID="@supermarket.ID">Go Inside</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
</table>

NowDelivary/Views/MenuCategory/GetSupermarketSections.cshtml
@model IEnumerable<MenuCategory>

@{
    ViewData["Title"] = "GetSupermarketSections";
}

<div class="container">
    <table class="table table-danger">
        <thead class="thead-dark">
            <tr>
                <th>Section Name</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{ 
                foreach (var sec in Model)
                {
                    <tr>
                        <td>@sec.MenuCategoryType</td>
                        <td>
                            <a class="btn btn-block btn-warning" asp-action="Edite" asp-route-id="@sec.ID">Edit</a>
                        </td>
                        <td>
                            <a class="btn btn-block btn-danger" asp-action="Delete" asp-route-id="@sec.ID">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a class="btn btn-block btn-info" asp-action="CreateMenuCategory">Add New Section</a>
</div>