NowDelivary/Models/PlaceCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NowDelivary.Models
{
    public class PlaceCategory
    {
        public int ID { get; set; }

        //[Index("IX_UniqueCategoryName",1,IsUnique =true)]
        public string PlaceCategoryName { get; set; }
    }
}

NowDelivary/Controllers/PlaceCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NowDelivary.Data;
using NowDelivary.Models;

namespace NowDelivary.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PlaceCategoryController : Controller
    {
        ApplicationDbContext _context;

        public PlaceCategoryController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        public IActionResult Index()
        {
            return View(_context.PlaceCategory.ToList());
        }

        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(PlaceCategory mod)
        {
            if (ModelState.IsValid)
            {
                _context.PlaceCategory.Add(mod);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
                return View(mod);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            PlaceCategory Mod = _context.PlaceCategory.Find(id);
            return View(Mod);
        }


        [HttpPost]
        public IActionResult Edit(PlaceCategory place)
        {
            if (ModelState.IsValid)
            {
                _context.PlaceCategory.Update(place);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
             return View(place);

        }

        public IActionResult Delete(int id)
        {
            PlaceCategory place = _context.PlaceCategory.Find(id);
            if (place == null)
            {
                return NotFound();
            }
            _context.PlaceCategory.Remove(place);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

NowDelivary/Views/PlaceCategory/Create.cshtml
@model NowDelivary.Models.PlaceCategory

@{
    ViewData["Title"] = "Create";
}



<h4>New Module</h4>
<hr />
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="PlaceCategoryName" class="control-label"></label>
                    <input asp-for="PlaceCategoryName" class="form-control" />
                    <span asp-validation-for="PlaceCategoryName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

  
    </div>

NowDelivary/Views/PlaceCategory/CreateModal.cshtml
@model NowDelivary.Models.PlaceCategory
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


   
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
                ×
            </button>
            <h4 class="modal-title">New Module</h4>
        </div>
        <div class="modal-body">

            <form asp-action="Create" asp-controller="PlaceCategory" method="post">

                <div class="form-group">
                    <label asp-for="PlaceCategoryName" class="control-label"></label>
                    <input asp-for="PlaceCategoryName" class="form-control" />
                    <span asp-validation-for="PlaceCategoryName" class="text-danger"></span>
                </div>

            </form>





        </div>
        <div class="modal-footer">

            <button type="submit" class="btn btn-success" onclick="DoCreate()">Create New Module</button>

        </div>
    </div>
</div>


<script>
    function DoCreate() {
        var Cat = $("#PlaceCategoryName").val();
        $.ajax({
            type: "POST",
            url: "/PlaceCategory/Create",
            data: '{Name: "' + Cat + '" }',
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (response) {
                window.location.reload();
            }
        });
    }
</script>
     

NowDelivary/Views/PlaceCategory/Edit.cshtml
@model NowDelivary.Models.PlaceCategory

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Module</h1>


<hr />
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" method="post">
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="PlaceCategoryName" class="control-label"></label>
                    <input asp-for="PlaceCategoryName" class="form-control" />
                    <span asp-validation-for="PlaceCategoryName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

NowDelivary/Views/PlaceCategory/Index.cshtml
@model IEnumerable<NowDelivary.Models.PlaceCategory>

@{
    ViewData["Title"] = "Index";
}

    <div class="container">
        <table class="table  table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.PlaceCategoryName)
                    </th>
                    <th>Action</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlaceCategoryName)
                        </td>
                        <td>
                            <a class="btn btn-block btn-info" asp-action="Edit" asp-controller="PlaceCategory" asp-route-id="@item.ID">Edit</a>
                        </td>
                        <td>
                            <a class="btn btn-block btn-danger" asp-action="Delete" asp-controller="PlaceCategory" asp-route-id="@item.ID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a asp-action="Create" class="btn btn-block btn-info" id="btnShowModal">ADD New Place Type</a>
    </div>