NowDelivary/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NowDelivary.Data;
using NowDelivary.Models;

namespace NowDelivary.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AreaController : Controller
    {
        ApplicationDbContext Context;
        public AreaController(ApplicationDbContext _context)
        {
            Context = _context;
        }

        //[Authorize(Roles = "admin")]
        public IActionResult GetAll()
        {
            return View(Context.Area.ToList());
        }

        public IActionResult CreateArea()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateArea(Area newArea)
        {
            if (ModelState.IsValid)
            {
                Context.Area.Add(newArea);
                Context.SaveChanges();
                return RedirectToAction("GetAll");
            }
            return View(newArea);
        }


        public IActionResult EditArea(int id)
        {
            
            Area area = Context.Area.Find(id);
            return View(area);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditArea(Area area)
        {
            if (ModelState.IsValid)
            {
                Context.Area.Update(area);
                Context.SaveChanges();
                return RedirectToAction("GetAll");
            }
             return View(area);

        }


        public IActionResult DeleteArea(int id)
        {
            Area area = Context.Area.Find(id);
            if (area == null)
            {
                return NotFound();
            }
            Context.Area.Remove(area);
            Context.SaveChanges();
            return RedirectToAction("GetAll");


        }
    }
}

NowDelivary/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NowDelivary.Data;
using NowDelivary.Models;
using NowDelivary.ViewModel;

namespace NowDelivary.Controllers
{
    public class MenuController : Controller
    {

        ApplicationDbContext Context;
        public MenuController(ApplicationDbContext _context)
        {
            
            Context = _context;
        }

        public IActionResult GetAll()
        {
            MenuVM menuVM = new MenuVM(this.Context);
            return View(menuVM);
        }

        public IActionResult CreateMenu()
        {
            ViewData["menucatID"] = new SelectList(Context.MenuCategorie, "ID", "MenuCategoryType");
            return View();
        }

        [HttpPost]
        public IActionResult CreateMenu(Menu newmenu)
        {
            if (ModelState.IsValid)
            {
                Context.Menu.Add(newmenu);
                Context.SaveChanges();
                return RedirectToAction("GetAll");
            }
            ViewData["menucatID"] = new SelectList(Context.MenuCategorie, "ID", "MenuCategoryType",newmenu.MenuCategoryID);

            return View(newmenu);
        }
        public async Task<IActionResult> Edite(int? id)
        {
            if(id==null)
            {
                return RedirectToAction("GetAll");
            }
            ViewData["menucatID"] = new SelectList(Context.MenuCategorie, "ID", "MenuCategoryType");

            var getmenudetails = await Context.Menu.FindAsync(id);
            return View(getmenudetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edite(Menu Me)
        {
            if(ModelState.IsValid)
            {
                Context.Update(Me);
                await Context.SaveChangesAsync();
                return RedirectToAction("GetAll");

            }
            ViewData["menucatID"] = new SelectList(Context.MenuCategorie, "ID", "MenuCategoryType", Me.MenuCategoryID);
            return View(Me);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("GetAll");
            }
            var getmenudetails = await Context.Menu.FindAsync(id);
            return View(getmenudetails);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
           
            var getmenudetails = await Context.Menu.FindAsync(id);
            Context.Menu.Remove(getmenudetails);
            await Context.SaveChangesAsync();
            return RedirectToAction("GetAll");
        }


        //public IActionResult Index()
        //{
        //    return View();
        //}
    }
}

NowDelivary/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NowDelivary.Data;
using NowDelivary.Models;
using NowDelivary.View_Model;

namespace NowDelivary.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PlacesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlacesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewData["AreaID"] = new SelectList(_context.Area, "ID", "AreaName");
            ViewData["PlaceCategoryID"] = new SelectList(_context.PlaceCategory, "ID", "PlaceCategoryName");
            return View();

        }

        public IActionResult GetFilteredPlaces(int areaID, int placeCategoryID)
        {
            PlaceVM vM = new PlaceVM(_context);
            return View(vM.FilterPlacesByAreaAndCategory(areaID,placeCategoryID));
        }

        public IActionResult Create()
        {
            ViewData["AreaID"] = new SelectList(_context.Area, "ID", "AreaName");
            ViewData["PlaceCategoryID"] = new SelectList(_context.PlaceCategory, "ID", "PlaceCategoryName");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Place place)
        {
            if (ModelState.IsValid)
            {
                _context.Place.Add(place);
                _context.SaveChanges();
             
                return RedirectToAction("Index");
            }
            ViewData["AreaID"] = new SelectList(_context.Area, "ID", "AreaName", place.AreaID);
            ViewData["PlaceCategoryID"] = new SelectList(_context.PlaceCategory, "ID", "PlaceCategoryName", place.PlaceCategoryID);
            return View(place);
        }

        public IActionResult Edit(int?id)
        {
            if (id == null)
            {
               return NotFound();
            }
            ViewData["AreaID"] = new SelectList(_context.Area, "ID", "AreaName");
            ViewData["PlaceCategoryID"] = new SelectList(_context.PlaceCategory, "ID", "PlaceCategoryName");
            Place place = _context.Place.Find(id);
            return View(place);
        }

        [HttpPost]
            public IActionResult Edit(Place place)
        {
            if (ModelState.IsValid)
            {
                _context.Place.Update(place);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["AreaID"] = new SelectList(_context.Area, "ID", "AreaName", place.AreaID);
            ViewData["PlaceCategoryID"] = new SelectList(_context.PlaceCategory, "ID", "PlaceCategoryName", place.PlaceCategoryID);
            return View(place);

        }

           public IActionResult Delete(int id)
        {
            Place place = _context.Place.Find(id);
            if (place == null)
            {
                return NotFound();
            }
            _context.Place.Remove(place);
            _context.SaveChanges();
            return RedirectToAction("Index");


        }
    }
}

NowDelivary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>NOW Delievery</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">


    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>

    <script src='https://kit.fontawesome.com/a076d05399.js'></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <!-- Template Main CSS File -->
    <link href="~/projectAssets/assets/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/projectAssets/assets/css/animate.min.css">
</head>

<body>
    <div class="wrapper">
        <nav class="navbar navbar-expand-lg fixed-top">
            <div class="container">
                <div class="navbar-header mr-auto mt-2 mt-lg-0">
                    <div class="navbar-left ">
                        <a style="text-decoration:none;color:white" asp-action="Index" asp-controller="Home">
                            <h1 class="brand brand-name navbar-left">
                                <i class="fas fa-biking" style="margin-right: 5px;"></i>NOW
                            </h1>
                        </a>
                    </div>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon" style="color:aqua;"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav mx-5 my-4 mr-auto">
                        <li><a id="len1" class="hoverable active" asp-action="Index" asp-controller="Home"><i class="fas fa-warehouse"></i>Home</a></li>
                        @if (User.IsInRole("Customer"))
                        {
                            <li>
                                <a asp-action="ShoppingCard" asp-controller="Customer" id="len4" class="hoverable">
                                    <i class="fas fa-shopping-cart"></i>
                                    shopping Card
                                </a>
                            </li>
                        }
                    </ul>
                    <div class=" my-2 my-lg-0">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>

        <!-- Content of Page -->
        <div class="container">
            <main role="main" class="pb-3">
                <div style="height:120px;"></div>
                @RenderBody()
            </main>
        </div>
        
        <div class="footer">
            <div class="footer-top">
                <!-- Negative cut out SVG -->
                <svg class="wave" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
                    <path fill="#fff"
                          fill-opacity="1"
                          d="M0,64L48,101.3C96,139,192,213,288,229.3C384,245,480,203,576,208C672,213,768,267,864,245.3C960,224,1056,128,1152,96C1248,64,1344,96,1392,112L1440,128L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z">
                        <text x="10" y="20" fill="black">I love SVG!</text>
                    </path>
                    <a xlink:href="#code">
                        <text x="50%" y="90%" margin-top=5px
                              font-family="sans-serif"
                              font-size="15px"
                              text-anchor="middle"
                              fill="black">CopyRight@NowDelivary.ITI minia Branch</text>
                    </a>
                </svg>
            </div>
        </div>

        <script src="~/projectAssets/assets/js/main.js"></script>

        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>

NowDelivary/Views/Shared/_adminLayout.cshtml
@{
    ViewData["Title"] = "AdminView";
}

<style>
    h1, p {
        text-align: center;
    }
</style>


<div class="container">
    <div class="row">
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">

                        <img src="~/projectAssets/assets/img/admin/area.jpg" style="width:300px;height:300px;" alt="pharm">
                    </div>
                    <div class="flip-card-back">
                        <h1>Areas</h1>
                        <p>This Part is for CRUD oprarions on site Areas</p>
                        <a asp-action="GetAll" asp-controller="Area" class="bubbly-button">Go</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="~/projectAssets/assets/img/admin/Deliveryman.png" style="width:300px;height:300px;" alt="pharm">
                    </div>
                    <div class="flip-card-back">
                        <h1>DelieveryMan </h1>
                        <p>This Part is for CRUD oprarions on site DelieveryMan</p>
                        <a asp-action="GetAllDelivarymen" asp-controller="Admin" class="bubbly-button">Go</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="~/projectAssets/assets/img/admin/places.png" style="width:300px;height:300px;" alt="pharm">
                    </div>
                    <div class="flip-card-back">
                        <h1>PlaceCategory </h1>
                        <p>This Part is for CRUD oprarions on site PlaceCategory</p>
                        <a asp-action="Index" asp-controller="PlaceCategory" class="bubbly-button">Go</a>
                    </div>
                </div>
            </div>
        </div>
        <br />
    </div>
    <br />
    <div class="row">
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="~/projectAssets/assets/img/admin/area1.jpg" style="width:300px;height:300px;" alt="pharm">
                    </div>
                    <div class="flip-card-back">
                        <h1>Places</h1>
                        <p>This Part is for CRUD oprarions on site places</p>
                        <a asp-action="Index" asp-controller="Places" class="bubbly-button">Go</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="~/projectAssets/assets/img/admin/menu.jpg" style="width:300px;height:300px;" alt="pharm">
                    </div>
                    <div class="flip-card-back">
                        <h1>Menues </h1>
                        <p>This Part is for CRUD oprarions on site Menues</p>
                        <a asp-action="GetAll" asp-controller="Menu" class="bubbly-button">Go</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="~/projectAssets/assets/img/admin/supplier.jpg" style="width:300px;height:300px;" alt="pharm">
                    </div>
                    <div class="flip-card-back">
                        <h1>MenueCategory</h1>
                        <p>This Part is for CRUD oprarions on site MenueCategory</p>
                        <a asp-action="GetAll" asp-controller="MenuCategory" class="bubbly-button">Go</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="~/projectAssets/assets/img/income.jpg" style="width:300px;height:300px;" alt="pharm">
                    </div>
                    <div class="flip-card-back">
                        <h1>Incom</h1>
                        <p>This Part is for Incom</p>
                        <a asp-action="IncomePage" asp-controller="Admin" class="bubbly-button">Go</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="~/projectAssets/assets/img/admin/deliverycost.png" style="width:300px;height:300px;" alt="pharm">
                    </div>
                    <div class="flip-card-back">
                        <h1>Delivary Cost</h1>
                        <p>This Part is for Set Delivary Cost Between Areas</p>
                        <a asp-action="SetDelivaryCostByArea" asp-controller="Admin" class="bubbly-button">Go</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>